---
title: AsposeBadServerResponceException
second_title: Référence de l'API Aspose.Email pour .NET
description: Initialise une nouvelle instance duAsposeBadServerResponceExceptionaspose.email/asposebadserverresponceexception classe avec un message derreur spécifié.
type: docs
weight: 10
url: /fr/net/aspose.email/asposebadserverresponceexception/asposebadserverresponceexception/
---
## AsposeBadServerResponceException(string) {#constructor_2}

Initialise une nouvelle instance du[`AsposeBadServerResponceException`](../../asposebadserverresponceexception) classe avec un message d'erreur spécifié.

```csharp
public AsposeBadServerResponceException(string message)
```

| Paramètre | Taper | La description |
| --- | --- | --- |
| message | String | Un message qui décrit l'erreur. |

### Voir également

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* espace de noms [Aspose.Email](../../asposebadserverresponceexception)
* Assemblée [Aspose.Email](../../../)

---

## AsposeBadServerResponceException() {#constructor}

Initialise une nouvelle instance du[`AsposeBadServerResponceException`](../../asposebadserverresponceexception) classe.

```csharp
public AsposeBadServerResponceException()
```

### Voir également

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* espace de noms [Aspose.Email](../../asposebadserverresponceexception)
* Assemblée [Aspose.Email](../../../)

---

## AsposeBadServerResponceException(string, Exception) {#constructor_3}

Initialise une nouvelle instance du[`AsposeBadServerResponceException`](../../asposebadserverresponceexception) classe avec un message d'erreur spécifié et une référence à l'exception interne qui est la cause de cette exception.

```csharp
public AsposeBadServerResponceException(string message, Exception innerException)
```

| Paramètre | Taper | La description |
| --- | --- | --- |
| message | String | Le message d'erreur qui explique la raison de l'exception. |
| innerException | Exception | L'exception qui est la cause de l'exception actuelle, ou une référence null (Nothing en Visual Basic) si aucune exception interne n'est spécifiée. |

### Voir également

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* espace de noms [Aspose.Email](../../asposebadserverresponceexception)
* Assemblée [Aspose.Email](../../../)

---

## AsposeBadServerResponceException(Exception) {#constructor_1}

Initialise une nouvelle instance du[`AsposeBadServerResponceException`](../../asposebadserverresponceexception) classe avec une référence à l'exception interne qui est la cause de cette exception.

```csharp
public AsposeBadServerResponceException(Exception innerException)
```

| Paramètre | Taper | La description |
| --- | --- | --- |
| innerException | Exception | L'exception qui est la cause de l'exception actuelle, ou une référence null (Nothing en Visual Basic) si aucune exception interne n'est spécifiée. |

### Voir également

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* espace de noms [Aspose.Email](../../asposebadserverresponceexception)
* Assemblée [Aspose.Email](../../../)

<!-- DO NOT EDIT: generated by xmldocmd for Aspose.Email.dll -->
