---
title: FileAccessViolationException
second_title: Aspose.Email for Java API Reference
description:  This exception wile be thrown when the file open and locked by another caller.
type: docs
weight: 242
url: /java/com.aspose.email/fileaccessviolationexception/
---
**Inheritance:**
java.lang.Object, java.lang.Throwable, java.lang.Exception, java.lang.RuntimeException, com.aspose.ms.System.Exception, com.aspose.ms.System.SystemException, com.aspose.ms.System.IO.IOException
```
public class FileAccessViolationException extends System.IO.IOException
```

This exception wile be thrown when the file open and locked by another caller.
## Constructors

| Constructor | Description |
| --- | --- |
| [FileAccessViolationException()](#FileAccessViolationException--) | Initializes a new instance of the class with default error message. |
| [FileAccessViolationException(String message)](#FileAccessViolationException-java.lang.String-) | Initializes a new instance of the class with a specified error message. |
| [FileAccessViolationException(String message, Throwable innerException)](#FileAccessViolationException-java.lang.String-java.lang.Throwable-) | Initializes a new instance of the Exception class with a specified error message and a reference to the inner exception that is the cause of this exception. |
### FileAccessViolationException() {#FileAccessViolationException--}
```
public FileAccessViolationException()
```


Initializes a new instance of the class with default error message.

### FileAccessViolationException(String message) {#FileAccessViolationException-java.lang.String-}
```
public FileAccessViolationException(String message)
```


Initializes a new instance of the class with a specified error message.

**Parameters:**
| Parameter | Type | Description |
| --- | --- | --- |
| message | java.lang.String | Error message. |

### FileAccessViolationException(String message, Throwable innerException) {#FileAccessViolationException-java.lang.String-java.lang.Throwable-}
```
public FileAccessViolationException(String message, Throwable innerException)
```


Initializes a new instance of the Exception class with a specified error message and a reference to the inner exception that is the cause of this exception.

**Parameters:**
| Parameter | Type | Description |
| --- | --- | --- |
| message | java.lang.String | The error message that explains the reason for the exception. |
| innerException | java.lang.Throwable | The exception that is the cause of the current exception. If the innerException parameter is not a NULL reference (Nothing in Visual Basic), the current exception is raised in a catch block that handles the inner exception. |

