---
title: AsposeBadServerResponceException
second_title: Aspose.Email for .NET API 参考
description: 使用指定的错误消息初始化AsposeBadServerResponceExceptionaspose.email/asposebadserverresponceexception类的新实例
type: docs
weight: 10
url: /zh/net/aspose.email/asposebadserverresponceexception/asposebadserverresponceexception/
---
## AsposeBadServerResponceException(string) {#constructor_2}

使用指定的错误消息初始化[`AsposeBadServerResponceException`](../../asposebadserverresponceexception)类的新实例。

```csharp
public AsposeBadServerResponceException(string message)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String | 描述错误的消息。 |

### 也可以看看

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* 命名空间 [Aspose.Email](../../asposebadserverresponceexception)
* 部件 [Aspose.Email](../../../)

---

## AsposeBadServerResponceException() {#constructor}

初始化[`AsposeBadServerResponceException`](../../asposebadserverresponceexception)类的新实例。

```csharp
public AsposeBadServerResponceException()
```

### 也可以看看

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* 命名空间 [Aspose.Email](../../asposebadserverresponceexception)
* 部件 [Aspose.Email](../../../)

---

## AsposeBadServerResponceException(string, Exception) {#constructor_3}

使用指定的错误消息初始化[`AsposeBadServerResponceException`](../../asposebadserverresponceexception)类 的新实例和对导致此异常的内部异常的引用。

```csharp
public AsposeBadServerResponceException(string message, Exception innerException)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String | 解释异常原因的错误消息。 |
| innerException | Exception | 导致当前异常的异常，如果没有内部异常，则为空引用（在 Visual Basic 中为空）被指定。 |

### 也可以看看

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* 命名空间 [Aspose.Email](../../asposebadserverresponceexception)
* 部件 [Aspose.Email](../../../)

---

## AsposeBadServerResponceException(Exception) {#constructor_1}

使用对内部的引用初始化[`AsposeBadServerResponceException`](../../asposebadserverresponceexception)类 的新实例异常是导致此异常的原因。

```csharp
public AsposeBadServerResponceException(Exception innerException)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| innerException | Exception | 导致当前异常的异常，或空引用（Nothing in Visual Basic) 如果没有指定内部异常。 |

### 也可以看看

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* 命名空间 [Aspose.Email](../../asposebadserverresponceexception)
* 部件 [Aspose.Email](../../../)

<!-- DO NOT EDIT: generated by xmldocmd for Aspose.Email.dll -->
