---
title: AsposeBadServerResponceException
second_title: Справочник по Aspose.Email для .NET API
description: Инициализирует новый экземпляр классаAsposeBadServerResponceExceptionaspose.email/asposebadserverresponceexceptionс указанным сообщением об ошибке.
type: docs
weight: 10
url: /ru/net/aspose.email/asposebadserverresponceexception/asposebadserverresponceexception/
---
## AsposeBadServerResponceException(string) {#constructor_2}

Инициализирует новый экземпляр класса[`AsposeBadServerResponceException`](../../asposebadserverresponceexception)с указанным сообщением об ошибке.

```csharp
public AsposeBadServerResponceException(string message)
```

| Параметр | Тип | Описание |
| --- | --- | --- |
| message | String | Сообщение, описывающее ошибку. |

### Смотрите также

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* пространство имен [Aspose.Email](../../asposebadserverresponceexception)
* сборка [Aspose.Email](../../../)

---

## AsposeBadServerResponceException() {#constructor}

Инициализирует новый экземпляр класса[`AsposeBadServerResponceException`](../../asposebadserverresponceexception).

```csharp
public AsposeBadServerResponceException()
```

### Смотрите также

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* пространство имен [Aspose.Email](../../asposebadserverresponceexception)
* сборка [Aspose.Email](../../../)

---

## AsposeBadServerResponceException(string, Exception) {#constructor_3}

Инициализирует новый экземпляр класса[`AsposeBadServerResponceException`](../../asposebadserverresponceexception) с указанным сообщением об ошибке и ссылка на внутреннее исключение, которое является причиной этого исключения.

```csharp
public AsposeBadServerResponceException(string message, Exception innerException)
```

| Параметр | Тип | Описание |
| --- | --- | --- |
| message | String | Сообщение об ошибке, объясняющее причину исключения. |
| innerException | Exception | Исключение, являющееся причиной текущего исключения, или пустая ссылка (Nothing в Visual Basic), если нет внутреннего исключения указано. |

### Смотрите также

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* пространство имен [Aspose.Email](../../asposebadserverresponceexception)
* сборка [Aspose.Email](../../../)

---

## AsposeBadServerResponceException(Exception) {#constructor_1}

Инициализирует новый экземпляр класса[`AsposeBadServerResponceException`](../../asposebadserverresponceexception) со ссылкой на внутренний исключение, которое является причиной этого исключения.

```csharp
public AsposeBadServerResponceException(Exception innerException)
```

| Параметр | Тип | Описание |
| --- | --- | --- |
| innerException | Exception | Исключение, являющееся причиной текущего исключения, или пустая ссылка (ничего в Visual Basic), если внутреннее исключение не указано. |

### Смотрите также

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* пространство имен [Aspose.Email](../../asposebadserverresponceexception)
* сборка [Aspose.Email](../../../)

<!-- DO NOT EDIT: generated by xmldocmd for Aspose.Email.dll -->
