---
title: SmtpException
second_title: Aspose.Email for .NET API 参考
description: 初始化 SmtpExceptionaspose.email/smtpexception 类的新实例
type: docs
weight: 10
url: /zh/net/aspose.email/smtpexception/smtpexception/
---
## SmtpException(SmtpStatusCode) {#constructor_1}

初始化 [`SmtpException`](../../smtpexception) 类的新实例

```csharp
public SmtpException(SmtpStatusCode statusCode)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| statusCode | SmtpStatusCode | Smtp状态码 |

### 也可以看看

* enum [SmtpStatusCode](../../../aspose.email.clients.smtp/smtpstatuscode)
* class [SmtpException](../../smtpexception)
* 命名空间 [Aspose.Email](../../smtpexception)
* 部件 [Aspose.Email](../../../)

---

## SmtpException(SmtpStatusCode, string) {#constructor_2}

初始化 [`SmtpException`](../../smtpexception) 类的新实例

```csharp
public SmtpException(SmtpStatusCode statusCode, string message)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| statusCode | SmtpStatusCode | Smtp状态码 |
| message | String | 错误信息 |

### 也可以看看

* enum [SmtpStatusCode](../../../aspose.email.clients.smtp/smtpstatuscode)
* class [SmtpException](../../smtpexception)
* 命名空间 [Aspose.Email](../../smtpexception)
* 部件 [Aspose.Email](../../../)

---

## SmtpException() {#constructor}

初始化 [`SmtpException`](../../smtpexception) 类的新实例

```csharp
public SmtpException()
```

### 也可以看看

* class [SmtpException](../../smtpexception)
* 命名空间 [Aspose.Email](../../smtpexception)
* 部件 [Aspose.Email](../../../)

---

## SmtpException(string) {#constructor_3}

初始化 [`SmtpException`](../../smtpexception) 类的新实例

```csharp
public SmtpException(string message)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String | 错误信息 |

### 也可以看看

* class [SmtpException](../../smtpexception)
* 命名空间 [Aspose.Email](../../smtpexception)
* 部件 [Aspose.Email](../../../)

---

## SmtpException(string, SendMessagesResult) {#constructor_4}

初始化 [`SmtpException`](../../smtpexception) 类的新实例

```csharp
public SmtpException(string message, SendMessagesResult result)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String | 错误信息 |
| result | SendMessagesResult | 操作结果 |

### 也可以看看

* class [SendMessagesResult](../../../aspose.email.clients.smtp/sendmessagesresult)
* class [SmtpException](../../smtpexception)
* 命名空间 [Aspose.Email](../../smtpexception)
* 部件 [Aspose.Email](../../../)

---

## SmtpException(string, Exception) {#constructor_6}

初始化 [`SmtpException`](../../smtpexception) 类的新实例

```csharp
public SmtpException(string message, Exception innerException)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String | 错误信息 |
| innerException | Exception | 导致当前异常的异常，如果未指定内部异常，则为空引用（Visual Basic 中为 Nothing）。 |

### 也可以看看

* class [SmtpException](../../smtpexception)
* 命名空间 [Aspose.Email](../../smtpexception)
* 部件 [Aspose.Email](../../../)

---

## SmtpException(string, Exception, MailMessage) {#constructor_7}

初始化 [`SmtpException`](../../smtpexception) 类的新实例

```csharp
public SmtpException(string message, Exception innerException, MailMessage mailMessage)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String | 错误信息 |
| innerException | Exception | 导致当前异常的异常，如果未指定内部异常，则为空引用（Visual Basic 中为 Nothing）。 |
| mailMessage | MailMessage |  |

### 也可以看看

* class [MailMessage](../../mailmessage)
* class [SmtpException](../../smtpexception)
* 命名空间 [Aspose.Email](../../smtpexception)
* 部件 [Aspose.Email](../../../)

---

## SmtpException(string, MailMessage) {#constructor_5}

```csharp
public SmtpException(string message, MailMessage mailMessage)
```

### 也可以看看

* class [MailMessage](../../mailmessage)
* class [SmtpException](../../smtpexception)
* 命名空间 [Aspose.Email](../../smtpexception)
* 部件 [Aspose.Email](../../../)

<!-- DO NOT EDIT: generated by xmldocmd for Aspose.Email.dll -->
