---
title: ActiveSyncException.ActiveSyncException
second_title: Aspose.Email for .NET API Reference
description: ActiveSyncException constructor. Initializes a new instance of the ActiveSyncException class with a specified error message
type: docs
weight: 10
url: /net/aspose.email/activesyncexception/activesyncexception/
---
## ActiveSyncException(string) {#constructor_2}

Initializes a new instance of the [`ActiveSyncException`](../) class with a specified error message.

```csharp
public ActiveSyncException(string message)
```

| Parameter | Type | Description |
| --- | --- | --- |
| message | String | A message that describes the error. |

### See Also

* class [ActiveSyncException](../)
* namespace [Aspose.Email](../../activesyncexception/)
* assembly [Aspose.Email](../../../)

---

## ActiveSyncException() {#constructor}

Initializes a new instance of the [`ActiveSyncException`](../) class.

```csharp
public ActiveSyncException()
```

### See Also

* class [ActiveSyncException](../)
* namespace [Aspose.Email](../../activesyncexception/)
* assembly [Aspose.Email](../../../)

---

## ActiveSyncException(string, Exception) {#constructor_3}

Initializes a new instance of the [`ActiveSyncException`](../) class with a specified error message and a reference to the inner exception that is the cause of this exception.

```csharp
public ActiveSyncException(string message, Exception innerException)
```

| Parameter | Type | Description |
| --- | --- | --- |
| message | String | The error message that explains the reason for the exception. |
| innerException | Exception | The exception that is the cause of the current exception, or a null reference (Nothing in Visual Basic) if no inner exception is specified. |

### See Also

* class [ActiveSyncException](../)
* namespace [Aspose.Email](../../activesyncexception/)
* assembly [Aspose.Email](../../../)

---

## ActiveSyncException(Exception) {#constructor_1}

Initializes a new instance of the [`ActiveSyncException`](../) class with a reference to the inner exception that is the cause of this exception.

```csharp
public ActiveSyncException(Exception innerException)
```

| Parameter | Type | Description |
| --- | --- | --- |
| innerException | Exception | The exception that is the cause of the current exception, or a null reference (Nothing in Visual Basic) if no inner exception is specified. |

### See Also

* class [ActiveSyncException](../)
* namespace [Aspose.Email](../../activesyncexception/)
* assembly [Aspose.Email](../../../)


