---
title: AsposeArgumentOutOfRangeException
second_title: Aspose.Email for .NET API 参考
description: 初始化AsposeArgumentOutOfRangeExceptionaspose.email/asposeargumentoutofrangeexception类的新实例
type: docs
weight: 10
url: /zh/net/aspose.email/asposeargumentoutofrangeexception/asposeargumentoutofrangeexception/
---
## AsposeArgumentOutOfRangeException() {#constructor}

初始化[`AsposeArgumentOutOfRangeException`](../../asposeargumentoutofrangeexception)类的新实例。

```csharp
public AsposeArgumentOutOfRangeException()
```

### 也可以看看

* class [AsposeArgumentOutOfRangeException](../../asposeargumentoutofrangeexception)
* 命名空间 [Aspose.Email](../../asposeargumentoutofrangeexception)
* 部件 [Aspose.Email](../../../)

---

## AsposeArgumentOutOfRangeException(string) {#constructor_2}

使用指定的错误消息初始化[`AsposeArgumentOutOfRangeException`](../../asposeargumentoutofrangeexception)类的新实例。

```csharp
public AsposeArgumentOutOfRangeException(string message)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String | 描述错误的消息。 |

### 也可以看看

* class [AsposeArgumentOutOfRangeException](../../asposeargumentoutofrangeexception)
* 命名空间 [Aspose.Email](../../asposeargumentoutofrangeexception)
* 部件 [Aspose.Email](../../../)

---

## AsposeArgumentOutOfRangeException(string, params object[]) {#constructor_5}

使用指定的错误消息初始化[`AsposeArgumentOutOfRangeException`](../../asposeargumentoutofrangeexception)类的新实例。

```csharp
public AsposeArgumentOutOfRangeException(string format, params object[] parameters)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| format | String | 消息格式 |
| parameters | Object[] | 格式参数 |

### 也可以看看

* class [AsposeArgumentOutOfRangeException](../../asposeargumentoutofrangeexception)
* 命名空间 [Aspose.Email](../../asposeargumentoutofrangeexception)
* 部件 [Aspose.Email](../../../)

---

## AsposeArgumentOutOfRangeException(string, int) {#constructor_3}

```csharp
public AsposeArgumentOutOfRangeException(string format, int parameter)
```

### 也可以看看

* class [AsposeArgumentOutOfRangeException](../../asposeargumentoutofrangeexception)
* 命名空间 [Aspose.Email](../../asposeargumentoutofrangeexception)
* 部件 [Aspose.Email](../../../)

---

## AsposeArgumentOutOfRangeException(string, Exception) {#constructor_4}

使用指定的错误消息初始化[`AsposeArgumentOutOfRangeException`](../../asposeargumentoutofrangeexception)类 的新实例和对导致此异常的内部异常的引用。

```csharp
public AsposeArgumentOutOfRangeException(string message, Exception innerException)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String | 解释异常原因的错误消息。 |
| innerException | Exception | 导致当前异常的异常，如果没有内部异常，则为空引用（在 Visual Basic 中为空）被指定。 |

### 也可以看看

* class [AsposeArgumentOutOfRangeException](../../asposeargumentoutofrangeexception)
* 命名空间 [Aspose.Email](../../asposeargumentoutofrangeexception)
* 部件 [Aspose.Email](../../../)

---

## AsposeArgumentOutOfRangeException(string, string) {#constructor_6}

```csharp
public AsposeArgumentOutOfRangeException(string message, string paramName)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String |  |
| paramName | String |  |

### 也可以看看

* class [AsposeArgumentOutOfRangeException](../../asposeargumentoutofrangeexception)
* 命名空间 [Aspose.Email](../../asposeargumentoutofrangeexception)
* 部件 [Aspose.Email](../../../)

---

## AsposeArgumentOutOfRangeException(Exception) {#constructor_1}

初始化[`AsposeArgumentOutOfRangeException`](../../asposeargumentoutofrangeexception)类 的新实例，并引用内部异常是导致此异常的原因。

```csharp
public AsposeArgumentOutOfRangeException(Exception innerException)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| innerException | Exception | 导致当前异常的异常，或空引用（Nothing in Visual Basic) 如果没有指定内部异常。 |

### 也可以看看

* class [AsposeArgumentOutOfRangeException](../../asposeargumentoutofrangeexception)
* 命名空间 [Aspose.Email](../../asposeargumentoutofrangeexception)
* 部件 [Aspose.Email](../../../)

<!-- DO NOT EDIT: generated by xmldocmd for Aspose.Email.dll -->
