---
title: AsposeBadServerResponceException
second_title: Aspose.Email für .NET-API-Referenz
description: Initialisiert eine neue Instanz vonAsposeBadServerResponceExceptionaspose.email/asposebadserverresponceexception Klasse mit einer bestimmten Fehlermeldung.
type: docs
weight: 10
url: /de/net/aspose.email/asposebadserverresponceexception/asposebadserverresponceexception/
---
## AsposeBadServerResponceException(string) {#constructor_2}

Initialisiert eine neue Instanz von[`AsposeBadServerResponceException`](../../asposebadserverresponceexception) Klasse mit einer bestimmten Fehlermeldung.

```csharp
public AsposeBadServerResponceException(string message)
```

| Parameter | Typ | Beschreibung |
| --- | --- | --- |
| message | String | Eine Meldung, die den Fehler beschreibt. |

### Siehe auch

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* namensraum [Aspose.Email](../../asposebadserverresponceexception)
* Montage [Aspose.Email](../../../)

---

## AsposeBadServerResponceException() {#constructor}

Initialisiert eine neue Instanz von[`AsposeBadServerResponceException`](../../asposebadserverresponceexception) Klasse.

```csharp
public AsposeBadServerResponceException()
```

### Siehe auch

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* namensraum [Aspose.Email](../../asposebadserverresponceexception)
* Montage [Aspose.Email](../../../)

---

## AsposeBadServerResponceException(string, Exception) {#constructor_3}

Initialisiert eine neue Instanz von[`AsposeBadServerResponceException`](../../asposebadserverresponceexception) Klasse mit einer angegebenen Fehlermeldung und einem Verweis auf die innere Ausnahme, die diese Ausnahme verursacht hat.

```csharp
public AsposeBadServerResponceException(string message, Exception innerException)
```

| Parameter | Typ | Beschreibung |
| --- | --- | --- |
| message | String | Die Fehlermeldung, die den Grund für die Ausnahme erklärt. |
| innerException | Exception | Die Ausnahme, die die Ursache der aktuellen Ausnahme ist, oder ein Nullverweis (Nothing in Visual Basic), wenn keine innere Ausnahme angegeben ist. |

### Siehe auch

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* namensraum [Aspose.Email](../../asposebadserverresponceexception)
* Montage [Aspose.Email](../../../)

---

## AsposeBadServerResponceException(Exception) {#constructor_1}

Initialisiert eine neue Instanz von[`AsposeBadServerResponceException`](../../asposebadserverresponceexception) Klasse mit einem Verweis auf die innere Ausnahme, die die Ursache dieser Ausnahme ist.

```csharp
public AsposeBadServerResponceException(Exception innerException)
```

| Parameter | Typ | Beschreibung |
| --- | --- | --- |
| innerException | Exception | Die Ausnahme, die die Ursache der aktuellen Ausnahme ist, oder ein Nullverweis (Nothing in Visual Basic), wenn keine innere Ausnahme angegeben ist. |

### Siehe auch

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* namensraum [Aspose.Email](../../asposebadserverresponceexception)
* Montage [Aspose.Email](../../../)

<!-- DO NOT EDIT: generated by xmldocmd for Aspose.Email.dll -->
