---
title: ActiveSyncException
second_title: Справочник по Aspose.Email для .NET API
description: Инициализирует новый экземпляр классаActiveSyncExceptionaspose.email/activesyncexceptionс указанным сообщением об ошибке.
type: docs
weight: 10
url: /ru/net/aspose.email/activesyncexception/activesyncexception/
---
## ActiveSyncException(string) {#constructor_2}

Инициализирует новый экземпляр класса[`ActiveSyncException`](../../activesyncexception)с указанным сообщением об ошибке.

```csharp
public ActiveSyncException(string message)
```

| Параметр | Тип | Описание |
| --- | --- | --- |
| message | String | Сообщение, описывающее ошибку. |

### Смотрите также

* class [ActiveSyncException](../../activesyncexception)
* пространство имен [Aspose.Email](../../activesyncexception)
* сборка [Aspose.Email](../../../)

---

## ActiveSyncException() {#constructor}

Инициализирует новый экземпляр класса[`ActiveSyncException`](../../activesyncexception).

```csharp
public ActiveSyncException()
```

### Смотрите также

* class [ActiveSyncException](../../activesyncexception)
* пространство имен [Aspose.Email](../../activesyncexception)
* сборка [Aspose.Email](../../../)

---

## ActiveSyncException(string, Exception) {#constructor_3}

Инициализирует новый экземпляр класса[`ActiveSyncException`](../../activesyncexception) с указанным сообщением об ошибке и ссылка на внутреннее исключение, которое является причиной этого исключения.

```csharp
public ActiveSyncException(string message, Exception innerException)
```

| Параметр | Тип | Описание |
| --- | --- | --- |
| message | String | Сообщение об ошибке, объясняющее причину исключения. |
| innerException | Exception | Исключение, являющееся причиной текущего исключения, или пустая ссылка (Nothing в Visual Basic), если нет внутреннего исключения указано. |

### Смотрите также

* class [ActiveSyncException](../../activesyncexception)
* пространство имен [Aspose.Email](../../activesyncexception)
* сборка [Aspose.Email](../../../)

---

## ActiveSyncException(Exception) {#constructor_1}

Инициализирует новый экземпляр класса[`ActiveSyncException`](../../activesyncexception) со ссылкой на внутренний исключение, которое является причиной этого исключения.

```csharp
public ActiveSyncException(Exception innerException)
```

| Параметр | Тип | Описание |
| --- | --- | --- |
| innerException | Exception | Исключение, являющееся причиной текущего исключения, или пустая ссылка (ничего в Visual Basic), если внутреннее исключение не указано. |

### Смотрите также

* class [ActiveSyncException](../../activesyncexception)
* пространство имен [Aspose.Email](../../activesyncexception)
* сборка [Aspose.Email](../../../)

<!-- DO NOT EDIT: generated by xmldocmd for Aspose.Email.dll -->
