---
title: AsposeBadServerResponceException
second_title: Aspose.Email for .NET API Reference
description: Initializes a new instance of the AsposeBadServerResponceExceptionaspose.email/asposebadserverresponceexception class with a specified error message.
type: docs
weight: 10
url: /net/aspose.email/asposebadserverresponceexception/asposebadserverresponceexception/
---
## AsposeBadServerResponceException(string) {#constructor_2}

Initializes a new instance of the [`AsposeBadServerResponceException`](../../asposebadserverresponceexception) class with a specified error message.

```csharp
public AsposeBadServerResponceException(string message)
```

| Parameter | Type | Description |
| --- | --- | --- |
| message | String | A message that describes the error. |

### See Also

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* namespace [Aspose.Email](../../asposebadserverresponceexception)
* assembly [Aspose.Email](../../../)

---

## AsposeBadServerResponceException() {#constructor}

Initializes a new instance of the [`AsposeBadServerResponceException`](../../asposebadserverresponceexception) class.

```csharp
public AsposeBadServerResponceException()
```

### See Also

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* namespace [Aspose.Email](../../asposebadserverresponceexception)
* assembly [Aspose.Email](../../../)

---

## AsposeBadServerResponceException(string, Exception) {#constructor_3}

Initializes a new instance of the [`AsposeBadServerResponceException`](../../asposebadserverresponceexception) class with a specified error message and a reference to the inner exception that is the cause of this exception.

```csharp
public AsposeBadServerResponceException(string message, Exception innerException)
```

| Parameter | Type | Description |
| --- | --- | --- |
| message | String | The error message that explains the reason for the exception. |
| innerException | Exception | The exception that is the cause of the current exception, or a null reference (Nothing in Visual Basic) if no inner exception is specified. |

### See Also

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* namespace [Aspose.Email](../../asposebadserverresponceexception)
* assembly [Aspose.Email](../../../)

---

## AsposeBadServerResponceException(Exception) {#constructor_1}

Initializes a new instance of the [`AsposeBadServerResponceException`](../../asposebadserverresponceexception) class with a reference to the inner exception that is the cause of this exception.

```csharp
public AsposeBadServerResponceException(Exception innerException)
```

| Parameter | Type | Description |
| --- | --- | --- |
| innerException | Exception | The exception that is the cause of the current exception, or a null reference (Nothing in Visual Basic) if no inner exception is specified. |

### See Also

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* namespace [Aspose.Email](../../asposebadserverresponceexception)
* assembly [Aspose.Email](../../../)

<!-- DO NOT EDIT: generated by xmldocmd for Aspose.Email.dll -->
