---
title: NetworkException
second_title: Aspose.Email for Java API Reference
description:  Thrown if there is a network connection failure.
type: docs
weight: 522
url: /java/com.aspose.email/networkexception/
---
**Inheritance:**
java.lang.Object, java.lang.Throwable, java.lang.Exception, java.lang.RuntimeException, com.aspose.ms.System.Exception
```
public class NetworkException extends System.Exception
```

Thrown if there is a network connection failure.
## Constructors

| Constructor | Description |
| --- | --- |
| [NetworkException()](#NetworkException--) | Initializes a new instance of the [NetworkException](../../com.aspose.email/networkexception) class. |
| [NetworkException(String message)](#NetworkException-java.lang.String-) | Initializes a new instance of the [NetworkException](../../com.aspose.email/networkexception) class. |
| [NetworkException(String message, System.Exception inner)](#NetworkException-java.lang.String-com.aspose.ms.System.Exception-) | Initializes a new instance of the [NetworkException](../../com.aspose.email/networkexception) class. |
### NetworkException() {#NetworkException--}
```
public NetworkException()
```


Initializes a new instance of the [NetworkException](../../com.aspose.email/networkexception) class.

### NetworkException(String message) {#NetworkException-java.lang.String-}
```
public NetworkException(String message)
```


Initializes a new instance of the [NetworkException](../../com.aspose.email/networkexception) class.

**Parameters:**
| Parameter | Type | Description |
| --- | --- | --- |
| message | java.lang.String | The error message. |

### NetworkException(String message, System.Exception inner) {#NetworkException-java.lang.String-com.aspose.ms.System.Exception-}
```
public NetworkException(String message, System.Exception inner)
```


Initializes a new instance of the [NetworkException](../../com.aspose.email/networkexception) class.

**Parameters:**
| Parameter | Type | Description |
| --- | --- | --- |
| message | java.lang.String | The error message. |
| inner | com.aspose.ms.System.Exception | The inner exception. |

