---
title: AsposeArgumentException
second_title: Aspose.Email for .NET API 参考
description: 初始化AsposeArgumentExceptionaspose.email/asposeargumentexception类的新实例
type: docs
weight: 10
url: /zh/net/aspose.email/asposeargumentexception/asposeargumentexception/
---
## AsposeArgumentException() {#constructor}

初始化[`AsposeArgumentException`](../../asposeargumentexception)类的新实例。

```csharp
public AsposeArgumentException()
```

### 也可以看看

* class [AsposeArgumentException](../../asposeargumentexception)
* 命名空间 [Aspose.Email](../../asposeargumentexception)
* 部件 [Aspose.Email](../../../)

---

## AsposeArgumentException(string) {#constructor_2}

使用指定的错误消息初始化[`AsposeArgumentException`](../../asposeargumentexception)类的新实例。

```csharp
public AsposeArgumentException(string message)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String | 描述错误的消息。 |

### 也可以看看

* class [AsposeArgumentException](../../asposeargumentexception)
* 命名空间 [Aspose.Email](../../asposeargumentexception)
* 部件 [Aspose.Email](../../../)

---

## AsposeArgumentException(string, string) {#constructor_5}

使用指定的错误消息初始化[`AsposeArgumentException`](../../asposeargumentexception)类的新实例。

```csharp
public AsposeArgumentException(string format, string parameter)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| format | String | 消息格式 |
| parameter | String |  |

### 也可以看看

* class [AsposeArgumentException](../../asposeargumentexception)
* 命名空间 [Aspose.Email](../../asposeargumentexception)
* 部件 [Aspose.Email](../../../)

---

## AsposeArgumentException(string, params object[]) {#constructor_4}

使用指定的错误消息初始化[`AsposeArgumentException`](../../asposeargumentexception)类的新实例。

```csharp
public AsposeArgumentException(string format, params object[] parameters)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| format | String | 消息格式 |
| parameters | Object[] | 格式参数 |

### 也可以看看

* class [AsposeArgumentException](../../asposeargumentexception)
* 命名空间 [Aspose.Email](../../asposeargumentexception)
* 部件 [Aspose.Email](../../../)

---

## AsposeArgumentException(string, Exception) {#constructor_3}

使用指定的错误消息初始化[`AsposeArgumentException`](../../asposeargumentexception)类 的新实例和对导致此异常的内部异常的引用。

```csharp
public AsposeArgumentException(string message, Exception innerException)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String | 解释异常原因的错误消息。 |
| innerException | Exception | 导致当前异常的异常，如果没有内部异常，则为空引用（在 Visual Basic 中为空）被指定。 |

### 也可以看看

* class [AsposeArgumentException](../../asposeargumentexception)
* 命名空间 [Aspose.Email](../../asposeargumentexception)
* 部件 [Aspose.Email](../../../)

---

## AsposeArgumentException(Exception) {#constructor_1}

使用对内部的引用初始化[`AsposeArgumentException`](../../asposeargumentexception)类 的新实例异常是导致此异常的原因。

```csharp
public AsposeArgumentException(Exception innerException)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| innerException | Exception | 导致当前异常的异常，或空引用（Nothing in Visual Basic) 如果没有指定内部异常。 |

### 也可以看看

* class [AsposeArgumentException](../../asposeargumentexception)
* 命名空间 [Aspose.Email](../../asposeargumentexception)
* 部件 [Aspose.Email](../../../)

<!-- DO NOT EDIT: generated by xmldocmd for Aspose.Email.dll -->
